-- NutriThai initial Supabase schema.
-- Run this in the Supabase SQL Editor after creating a Supabase project.

create table if not exists public.profiles (
    id uuid primary key references auth.users (id) on delete cascade,
    username text not null check (char_length(trim(username)) between 3 and 50),
    gender text not null check (gender in ('male', 'female')),
    weight_kg numeric(6, 2) not null check (weight_kg between 20 and 500),
    height_cm numeric(6, 2) not null check (height_cm between 100 and 250),
    age integer not null check (age between 10 and 120),
    activity_level text not null check (
        activity_level in ('sedentary', 'light', 'moderate', 'active')
    ),
    goal text not null check (goal in ('lose_weight', 'maintain', 'gain_muscle')),
    timezone text not null default 'Asia/Bangkok',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.foods (
    id bigint generated by default as identity primary key,
    food_code text unique,
    name text not null check (char_length(trim(name)) > 0),
    english_name text,
    category text not null check (category in ('food', 'drink', 'dessert')),
    calories numeric(8, 2) not null check (calories >= 0),
    protein numeric(8, 2) not null default 0 check (protein >= 0),
    carbs numeric(8, 2) not null default 0 check (carbs >= 0),
    fat numeric(8, 2) not null default 0 check (fat >= 0),
    sugar numeric(8, 2) not null default 0 check (sugar >= 0),
    fiber numeric(8, 2) not null default 0 check (fiber >= 0),
    created_at timestamptz not null default now()
);

create table if not exists public.food_logs (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users (id) on delete cascade,
    food_id bigint references public.foods (id) on delete set null,
    source text not null default 'catalog' check (source in ('catalog', 'ai', 'custom')),
    food_name text not null check (char_length(trim(food_name)) > 0),
    food_name_th text,
    meal_type text not null check (
        meal_type in ('breakfast', 'lunch', 'dinner', 'snack')
    ),
    servings numeric(8, 3) not null check (servings > 0 and servings <= 100),
    calories_per_serving numeric(8, 2) not null check (calories_per_serving >= 0),
    protein_per_serving numeric(8, 2) not null default 0 check (protein_per_serving >= 0),
    carbs_per_serving numeric(8, 2) not null default 0 check (carbs_per_serving >= 0),
    fat_per_serving numeric(8, 2) not null default 0 check (fat_per_serving >= 0),
    sugar_per_serving numeric(8, 2) not null default 0 check (sugar_per_serving >= 0),
    fiber_per_serving numeric(8, 2) not null default 0 check (fiber_per_serving >= 0),
    meal_date date not null,
    logged_at timestamptz not null default now(),
    created_at timestamptz not null default now()
);

create index if not exists food_logs_user_meal_date_idx
    on public.food_logs (user_id, meal_date desc);
create index if not exists food_logs_food_id_idx
    on public.food_logs (food_id);

create schema if not exists extensions;

do $$
declare
    trigram_schema name;
begin
    if not exists (select 1 from pg_extension where extname = 'pg_trgm') then
        execute 'create extension pg_trgm with schema extensions';
    end if;

    select namespace.nspname
    into trigram_schema
    from pg_extension as extension
    join pg_namespace as namespace on namespace.oid = extension.extnamespace
    where extension.extname = 'pg_trgm';

    execute format(
        'create index if not exists foods_name_trgm_idx on public.foods using gin (name %I.gin_trgm_ops)',
        trigram_schema
    );
    execute format(
        'create index if not exists foods_english_name_trgm_idx on public.foods using gin (english_name %I.gin_trgm_ops)',
        trigram_schema
    );
end;
$$;

create or replace function public.search_foods(
    search_query text,
    result_limit integer default 8,
    category_filter text default null
)
returns setof public.foods
language sql
stable
security invoker
set search_path = public, extensions
as $$
    select food.*
    from public.foods as food
    where btrim(search_query) <> ''
      and (
          food.name ilike '%' || btrim(search_query) || '%'
          or food.english_name ilike '%' || btrim(search_query) || '%'
      )
      and (category_filter is null or food.category = category_filter)
    order by food.name
    limit greatest(1, least(coalesce(result_limit, 8), 50));
$$;

grant execute on function public.search_foods(text, integer, text) to anon, authenticated;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
    before update on public.profiles
    for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.foods enable row level security;
alter table public.food_logs enable row level security;

revoke all on public.profiles, public.foods, public.food_logs from anon, authenticated;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile"
    on public.profiles for select to authenticated
    using ((select auth.uid()) = id);

drop policy if exists "Users can create their own profile" on public.profiles;
create policy "Users can create their own profile"
    on public.profiles for insert to authenticated
    with check ((select auth.uid()) = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
    on public.profiles for update to authenticated
    using ((select auth.uid()) = id)
    with check ((select auth.uid()) = id);

drop policy if exists "Foods are readable by everyone" on public.foods;
create policy "Foods are readable by everyone"
    on public.foods for select to anon, authenticated
    using (true);

drop policy if exists "Users can read their own food logs" on public.food_logs;
create policy "Users can read their own food logs"
    on public.food_logs for select to authenticated
    using ((select auth.uid()) = user_id);

drop policy if exists "Users can create their own food logs" on public.food_logs;
create policy "Users can create their own food logs"
    on public.food_logs for insert to authenticated
    with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own food logs" on public.food_logs;
create policy "Users can update their own food logs"
    on public.food_logs for update to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own food logs" on public.food_logs;
create policy "Users can delete their own food logs"
    on public.food_logs for delete to authenticated
    using ((select auth.uid()) = user_id);

grant select on public.foods to anon, authenticated;
grant select, insert, update, delete
    on public.profiles, public.food_logs to authenticated;
